#!/usr/bin/env bash

cd $(dirname $0)/..
set -e
set -o pipefail

if [ -z ${CIRCLECI+x} ]; then
    echo "Not on Circle; refusing to run."
    exit 1
fi

echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
chmod 0600 .npmrc

echo "Copying files into build/ directory..."
npm run copy

echo "Publishing build/ directory..."
npm publish build/
